create table landing_product (
	p_Id varchar (32) not null,
	p_Name varchar (64) not null,
	NameLower varchar (128) not null,
	BaseValue int,
	Consumable boolean not null,
	ChargeValue int,
	StackMultiplier int,
	DefaultCraftAmount int,
	CraftAmountStepSize int,
	RecipeCost int,
	SpecificChargeOnly boolean not null,
	NormalisedValueOnWorld varchar (128),
	NormalisedValueOffWorld varchar (128),
	WikiCategory varchar (64) not null,
	IsCraftable boolean not null,
	DeploysInto varchar (32),
	EconomyInfluenceMultiplier real,
	CookingIngredient boolean not null,
	GoodForSelling boolean not null,
	SubstanceCategory varchar (64),
	ProductCategory varchar (64) not null,
	Rarity varchar (32) not null,
	Legality varchar (32) not null,
	SpaceStationMarkup real,
	LowPriceMod real,
	HighPriceMod real,
	BuyBaseMarkup real,
	BuyMarkupMod real,
	TradingClass varchar(32),
	HasRequirements boolean not null
);