insert into landing_substance (
	s_id,
	s_name,
	name_lower,
	base_value,
	substance_category,
	rarity,
	legality,
	charge_value,
	stack_multiplier,
	space_station_markup,
	low_price_mod,
	high_price_mod,
	buy_base_markup,
	buy_markup_mod,
	normalised_value_on_world,
	normalised_value_off_world,
	trading_class,
	economy_influence_multiplier,
	cooking_ingredient,
	good_for_selling
) values (
	{{ID as str}},
	{{Name as str}},
	{{NameLower as str}},
	{{BaseValue as int}},
	{{SubstanceCategory as str}},
	{{Rarity as str}},
	{{Legality as str}},
	{{ChargeValue as int}},
	{{StackMultiplier as int}},
	{{SpaceStationMarkup as real}},
	{{LowPriceMod as real}},
	{{HighPriceMod as real}},
	{{BuyBaseMarkup as real}},
	{{BuyMarkupMod as real}},
	{{NormalisedValueOnWorld as str}},
	{{NormalisedValueOffWorld as str}},
	{{TradingClass as str}},
	{{EconomyInfluenceMultiplier as real}},
	{{CookingIngredient as bool}},
	{{GoodForSelling as bool}}
);
