insert into landing_product (
	p_Id,
	p_Name,
	NameLower,
	BaseValue,
	Consumable,
	ChargeValue,
	StackMultiplier,
	DefaultCraftAmount,
	CraftAmountStepSize,
	RecipeCost,
	SpecificChargeOnly,
	NormalisedValueOnWorld,
	NormalisedValueOffWorld,
	WikiCategory,
	IsCraftable,
	DeploysInto,
	EconomyInfluenceMultiplier,
	CookingIngredient,
	GoodForSelling,
	SubstanceCategory,
	ProductCategory,
	Rarity,
	Legality,
	SpaceStationMarkup,
	LowPriceMod,
	HighPriceMod,
	BuyBaseMarkup,
	BuyMarkupMod,
	TradingClass,
	HasRequirements
) values (
	{{Id as str}},
	{{Name as str}},
	{{NameLower as str}},
	{{BaseValue as int}},
	{{Consumable as bool}},
	{{ChargeValue as int}},
	{{StackMultiplier as int}},
	{{DefaultCraftAmount as int}},
	{{CraftAmountStepSize as int}},
	{{RecipeCost as int}},
	{{SpecificChargeOnly as bool}},
	{{NormalisedValueOnWorld as str}},
	{{NormalisedValueOffWorld as str}},
	{{WikiCategory as str}},
	{{IsCraftable as bool}},
	{{DeploysInto as str}},
	{{EconomyInfluenceMultiplier as real}},
	{{CookingIngredient as bool}},
	{{GoodForSelling as bool}},
	{{SubstanceCategory as str}},
	{{ProductCategory as str}},
	{{Rarity as str}},
	{{Legality as str}},
	{{SpaceStationMarkup as real}},
	{{LowPriceMod as real}},
	{{HighPriceMod as real}},
	{{BuyBaseMarkup as real}},
	{{BuyMarkupMod as real}},
	{{TradingClass as str}},
	{{HasRequirements as bool}}
);
