create table landing_substance (
	s_id varchar (32) not null,
	s_name varchar (64) not null,
	name_lower varchar (128) not null,
	base_value int,
	substance_category varchar (64),
	rarity varchar (32) not null,
	legality varchar (32) not null,
	charge_value int,
	stack_multiplier int,
	space_station_markup real,
	low_price_mod real,
	high_price_mod real,
	buy_base_markup real,
	buy_markup_mod real,
	normalised_value_on_world varchar (128),
	normalised_value_off_world varchar (128),
	trading_class varchar(32),
	economy_influence_multiplier real,
	cooking_ingredient boolean not null,
	good_for_selling boolean not null
);